

services:
  autotesthub:
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./reports:/app/reports
      - ./input:/app/input
      - ./output:/app/output
      - ./expected:/app/expected
      - ./code:/app/code
    command: python src/runner.py

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
